[package]
name = "krebs"
version = "0.1.0"
authors = ["chickenbreeder <chickenbreeder@users.noreply.github.com>"]
license = "MIT"
repository = "https://github.com/chickenbreeder/krebs"
description = "Tiny webframework"

[dependencies]
hyper = "0.11.2"
futures = "0.1.14"
